#@ load("@ytt:data", "data")

apiVersion: v1
kind: Namespace
metadata:
  name: kdc
---
kind: Service
apiVersion: v1
metadata:
  name: kdc
  labels:
    app: kdc
  namespace: kdc
spec:
  selector:
    app: kdc
  type: ClusterIP
  ports:
    - name: kerberos-kdc-tcp
      port: 88
      protocol: TCP
    - name: kerberos-kdc
      port: 88
      protocol: UDP
    - name: kpasswd
      port: 464
      protocol: UDP
    - name: kadmin
      port: 749
      protocol: UDP
    - name: kadmin-tcp
      port: 749
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdc
  namespace: kdc
spec:
  selector:
    matchLabels:
      app: kdc
  template:
    metadata:
      labels:
        app: kdc
    spec:
      containers:
      - name: kdc
        image: gcavalcante8808/krb5-server
        resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 300m
        ports:
          - containerPort: 749
            protocol: TCP
          - containerPort: 749
            protocol: UDP
          - containerPort: 464
            protocol: UDP
          - containerPort: 888
            protocol: TCP
          - containerPort: 888
            protocol: UDP
        env:
          - name: KRB5_REALM
            value: #@ data.values.kdc.realm
          - name: KRB5_KDC
            value: #@ data.values.kdc.host
          - name: KRB5_PASS
            value: #@ data.values.kdc.admin_password
