#@ load("@ytt:data", "data")
---
apiVersion: conventions.carto.run/v1alpha1
kind: ClusterPodConvention
metadata:
  name: kerberos-convention-server
spec:
  webhook:
    clientConfig:
      url: #@ data.values.convention_server.url + '/webhook'
