apiVersion: conventions.carto.run/v1alpha1
kind: ClusterPodConvention
metadata:
  name: kerberos-convention-server
spec:
  webhook:
    certificate:
      name: kerberos-sidecar-convention-webhook-cert
      namespace: kerberos-sidecar-convention
    clientConfig:
      service:
        name: kerberos-sidecar-convention-webhook
        namespace: kerberos-sidecar-convention
        path: "/webhook"
