apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: custom-sql-dack-pack-builder
spec:
  order:
  - group:
    - id: CUSTOM_BUILD_PACK
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  stack:
    kind: ClusterStack
    name: sql-dack-pack
  store:
    kind: ClusterStore
    name: default
  tag: winterfell2.azurecr.io/tap/tbs:clusterbuilder-custom-sql-dack-pack-builder