#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: run-ca-certs
data:
  cert-1: #@ data.values.mssql.ca_cert
---
apiVersion: stacks.stacks-operator.tanzu.vmware.com/v1alpha1
kind: CustomStack
metadata:
  name: base-kerberos
spec:
  source:
    stack:
      name: base
      kind: ClusterStack
  destination:
    build:
      tag: #@ data.values.build_service_repository_prefix + '/base-kerberos-build'
    run:
      tag: #@ data.values.build_service_repository_prefix + '/base-kerberos-run'
    stack: 
      name: base-kerberos
      kind: ClusterStack
  packages:
    - name: krb5-user
      phase: run
  caCerts:
    runRef:
      name: run-ca-certs