#@ load("@ytt:data", "data")

---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: base-kerberos
spec:
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core-lite
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  stack:
    kind: ClusterStack
    name: base-kerberos
  store:
    kind: ClusterStore
    name: default
  tag: #@ data.values.build_service_repository_prefix + '/base-kerberos-builder'