#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: kerberos-demo-ad-run-as-user
  labels: 
    service: "ad-run-as"
    user: #@ data.values.dev_namespace
  namespace: service-instances-ad-run-as
type: Opaque
stringData:
  type: ActiveDirectory
  username: #@ data.values.kerberos_demo_app.krb_service_account
  password: #@ data.values.kerberos_demo_app.krb_password
  host: #@ data.values.kerberos_demo_app.ad_host
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: #@ 'ad-run-as-' + data.values.dev_namespace
  namespace: service-instances-ad-run-as
spec:
  consumingNamespaces:
  - #@ data.values.dev_namespace
  subject:
    group: ""
    kind: Secret #! Needs to be singular with first letter capital
    selector:
      matchLabels:
        service: "ad-run-as"
        user: #@ data.values.dev_namespace
