#@ load("@ytt:data", "data")

---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: kerberos-demo-tbs
  namespace: #@ data.values.dev_namespace
spec:
  build:
    env:
    - name: BP_DOTNET_PROJECT_PATH
      value: sample/KerberosDemo
    resources: {}
  builder:
    kind: ClusterBuilder
    name: base-kerberos
  cache:
    volume:
      size: 2G
  failedBuildHistoryLimit: 10
  serviceAccountName: default
  source:
    git:
      url: https://github.com/macsux/kerberos-buildpack
      revision: main
      subPath: sample
  successBuildHistoryLimit: 10
  tag: #@ data.values.build_service_repository_prefix + '/sc/kerberos-demo-tbs'
