apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: kerberos-demo
  labels:
    apps.tanzu.vmware.com/workload-type: kerberos-web
    app.kubernetes.io/part-of: kerberos-demo
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: "base-kerberos"
  build:
    env:
    - name: BP_DOTNET_PROJECT_PATH
      value: KerberosDemo
  source:
    git:
      url: https://github.com/macsux/kerberos-buildpack
      ref:
        branch: main
    subPath: sample