apiVersion: conventions.carto.run/v1alpha1
kind: ClusterPodConvention
metadata:
  name: kerberos-convention-server-2
spec:
  webhook:
    certificate:
      name: awesome-webhook-cert
      namespace: awesome-convention
    clientConfig:
      service:
        name: awesome-webhook
        namespace: awesome-convention
        path: "/webhook"
