apiVersion: v1
kind: Namespace
metadata:
  name: service-instances-mssql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-claims-mssql
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"] #! Needs to be lower case and plural
    verbs: ["get", "list", "watch"]

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: mssql
spec:
  description:
    short: It's an external reference to a Sql Server DB!
  pool:
    kind: Secret #! Needs to be singular with first letter capital
    labelSelector:
      matchLabels:
        service: "mssql"
---