apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit-ingress
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-edit-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit-ingress
subjects:
  - kind: ServiceAccount
    name: default
